spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=FALSE
#    url: jdbc:mysql://localhost:3306/sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=FALSE
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.112
    port: 6379
    password:
server:
  context-path: /sell

logging:
  pattern:
    console: "%d -- %msg%n"

wechat:
  mpAppId: wxa4320fd910208b9e                      #测试账号
  mpAppSecret: 50d1824c0696b2b9a70a5e96843bff26    #测试账号
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
#  mchId: 1483469312
  mchId: 1409146202
#  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: D:/weixin_cert/h5.p12
  notifyUrl: http://xuren2012.natapp1.cc/sell/pay/notify
  templatedId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: xuren2012.natapp1.cc
  wechatOpenAuthorize: xuren2012.natapp1.cc
  sell: xuren2012.natapp1.cc

mybatis:
  mapper-locations: classpath:mapper/*.xml